// Centralized DOM rules. Exact labels, never coordinates or constructed routes.
export const SELECTORS={
 overview:{css:['[data-probe-action="overview"]'],labels:['整体数据','整体分析']},
 content:{css:['[data-probe-action="content"]'],labels:['内容分析']},
 audience:{css:['[data-probe-action="audience"]'],labels:['观众分析']},
 traffic:{css:['[data-probe-action="traffic"]'],labels:['流量分析']},
 revenue:{css:['[data-probe-action="revenue"]'],labels:['营收','营收指标']},
 trend:{css:['[data-probe-action="trend"]'],labels:['流量','流量指标']},
 interaction:{css:['[data-probe-action="interaction"]'],labels:['互动指标','互动']},
 fans:{css:['[data-probe-action="fans"]'],labels:['粉丝','粉丝指标']},
 text:{css:['[data-probe-action="text"]'],labels:['文字记录','主播文字记录']},
 comments:{css:['[data-probe-action="comments"]'],labels:['直播间评论','直播评论']},
 gifts:{css:['[data-probe-action="gifts"]'],labels:['直播间礼物','直播礼物']},
 clips:{css:['[data-probe-action="clips"]'],labels:['关键片段']},
 controls:'button,a,[role="tab"],[role="button"],.ant-tabs-tab,label,div,span',
 clickableControls:'button,a,label,[role="tab"],[role="button"],[role="menuitem"]',
 clickableClasses:'(?:^|\\s)(?:side-menu-item|ant-menu-item|ant-menu-submenu-title|ant-tabs-tab|menu-item)(?:\\s|$|[-_])',
 maxControlAncestorDepth:6,
 maxControlDescendants:40,
 textPanels:['[data-probe-text-panel]','[data-testid="text-records"]','[aria-label="文字记录"]','[class*="transcript"]','[class*="text-record"]'],
 textPrevious:['[data-probe-text-previous]','button[aria-label="上一页"]','.ant-pagination-prev button'],
 textFirst:['[data-probe-text-first]','button[aria-label="第一页"]'],
 textNext:['[data-probe-text-next]','button[aria-label="下一页"]','button[title="下一页"]','.ant-pagination-next button','.ant-pagination-next a'],
 textSlider:'[role="slider"],.ant-slider-handle,.ant-slider',
 contentPanels:['[data-probe-content-panel]','[role="tabpanel"][aria-hidden="false"]','.ant-tabs-tabpane-active'],
 textDiagnosticLabels:['文字记录','主播文字记录','上一页','下一页','第一页','最后一页','前一段','后一段','评论','直播间评论','粉丝','流量','互动指标'],
 textRange:['input[type="range"][aria-label*="时间"]','input[type="range"][data-probe-text-range]'],
 liveStart:['[data-live-start]','time[data-testid="live-start"]'],liveEnd:['[data-live-end]','time[data-testid="live-end"]'],
 reviewRoute:'^/(?:anchor/(?:review|replay)|review|replay|live_detail|room/detail)(?:/|$)',
};
export const STEPS=[
 {id:'overview',state:'NAVIGATING_OVERVIEW',module:'overview'},
 {id:'content',state:'NAVIGATING_CONTENT',module:'content'},
 {id:'revenue',state:'CAPTURING',module:'content',optional:true},
 {id:'trend',state:'CAPTURING',module:'content',optional:true},
 {id:'interaction',state:'CAPTURING',module:'content',optional:true},
 {id:'fans',state:'CAPTURING',module:'content',optional:true},
 {id:'text',state:'COLLECTING_TEXT',module:'text'},
 {id:'comments',state:'COLLECTING_COMMENTS',module:'comments'},
 {id:'gifts',state:'CAPTURING',module:'content',optional:true},
 {id:'clips',state:'CAPTURING',module:'content',optional:true},
 {id:'audience',state:'NAVIGATING_AUDIENCE',module:'audience'},
 {id:'traffic',state:'NAVIGATING_TRAFFIC',module:'traffic'},
];
