import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const listeners={};let stored,bodyCalls=0,detached=0,attachCalls=0;let failBody=false;
const emitter=name=>({addListener(fn){listeners[name]=fn;}});
globalThis.indexedDB={open(){const r={};queueMicrotask(()=>{r.result={createObjectStore(){},close(){},transaction(){const tx={objectStore(){return {get(){const g={};queueMicrotask(()=>{g.result=stored;g.onsuccess();tx.oncomplete?.();});return g;},put(s){stored=structuredClone(s);queueMicrotask(()=>tx.oncomplete());}};}};return tx;}};r.onsuccess();});return r;}};
globalThis.chrome={runtime:{id:'fake-extension',onMessage:emitter('message')},debugger:{onEvent:emitter('event'),onDetach:emitter('detach'),async attach(){attachCalls++;},async detach(){detached++;},async sendCommand(target,method){if(['Network.enable','Page.enable'].includes(method))return {};assert.equal(method,'Network.getResponseBody');bodyCalls++;if(failBody)throw Error('Private unsafe error');return {body:fs.readFileSync('mocks/minute_trend.mock.json','utf8')};}},tabs:{onUpdated:emitter('updated'),onRemoved:emitter('removed'),async get(id){return {id,url:id===1?'https://anchor.douyin.com/review?token=FAKE_PRIVATE':'https://example.com/'};}}};
await import('../extension/src/background/service-worker.js');
const message=m=>new Promise(resolve=>listeners.message(m,{id:'fake-extension'},resolve));
const event=(e,p)=>listeners.event({tabId:1},e,p);
const response=(id,mime='application/json',type='XHR')=>{event('Network.requestWillBeSent',{requestId:id,request:{method:'GET',headers:{Cookie:'NEVER_PERSIST'},postData:'PRIVATE'}});event('Network.responseReceived',{requestId:id,type,response:{url:'https://anchor.douyin.com/api/'+id+'?token=NEVER_PERSIST',mimeType:mime,status:200,headers:{'Set-Cookie':'NEVER_PERSIST'}}});event('Network.loadingFinished',{requestId:id});};
test('后台开始 / 加载结束取正文 / 跳过图片 / 本地持久化',async()=>{assert((await message({type:'start',tabId:1})).ok);response('minute_trend');response('image','image/png','Image');const r=await message({type:'export'});assert.equal(bodyCalls,1);assert.equal(r.session.endpoints['anchor.douyin.com /api/minute_trend GET'].schema.arrays[0].time_series.median_interval_seconds,60);assert(!JSON.stringify(stored).includes('NEVER_PERSIST'));assert(!JSON.stringify(stored).includes('FAKE_PRIVATE'));});
test('正文不可读保留 metadata，不持久化错误原文',async()=>{failBody=true;response('unavailable');const r=await message({type:'export'});assert.equal(r.session.endpoints['anchor.douyin.com /api/unavailable GET'].metadata[0].body_status,'BODY_UNAVAILABLE');assert(!JSON.stringify(stored).includes('Private unsafe'));});
test('停止立即 detach，停止后事件无效',async()=>{const before=bodyCalls;assert.equal((await message({type:'stop'})).tabId,null);assert.equal(detached,1);response('after_stop');await message({type:'status'});assert.equal(bodyCalls,before);});
test('错误域名拒绝，清空本地缓存',async()=>{assert(!(await message({type:'start',tabId:2})).ok);assert.equal(attachCalls,1);const r=await message({type:'clear'});assert.equal(Object.keys(r.session.endpoints).length,0);assert.equal(stored.bodyBytes,0);});

test('顶层页面导航范围外自动 detach',async()=>{failBody=false;assert((await message({type:'start',tabId:1})).ok);event('Page.frameNavigated',{frame:{url:'https://other.example/'}});const r=await message({type:'status'});assert.equal(r.tabId,null);assert.equal(detached,2);});

test('开始 attach 尚未完成时停止，不能重新进入采集',async()=>{let finish,entered;const gate=new Promise(r=>entered=r);chrome.debugger.attach=async()=>{entered();await new Promise(r=>finish=r);};const starting=message({type:'start',tabId:1});await gate;await message({type:'stop'});finish();assert.equal((await starting).ok,false);assert.equal((await message({type:'status'})).tabId,null);});
