import test from 'node:test';import assert from 'node:assert/strict';
import {pageOperation} from '../extension/src/automation/page-controller.js';
import {SELECTORS} from '../extension/src/automation/selectors.js';
import {ReviewNavigator} from '../extension/src/automation/review-navigator.js';
import {AutoCollector} from '../extension/src/automation/collector-state-machine.js';
// Minimal DOM test fixture; browser regressions below also use real Chromium DOM.
class Element{
 constructor(tag,text='',attrs={},children=[]){this.tagName=tag.toUpperCase();this.text=text;this.attrs=attrs;this.children=children;this.clicked=0;for(const child of children)child.parentElement=this;}
 get innerText(){return this.text+this.children.map(c=>c.innerText).join('');}get textContent(){return this.innerText;}
 getAttribute(key){return this.attrs[key]??null;}getClientRects(){return this.attrs.hidden||this.parentElement&&!this.parentElement.getClientRects().length?[]:[{}];}
 contains(other){return this.children.some(c=>c===other||c.contains(other));}
 matches(query){return query.split(',').some(raw=>{const selector=raw.trim();if(selector.startsWith('.'))return (this.attrs.class||'').split(/\s+/).includes(selector.slice(1));const m=selector.match(/^\[([^=\]]+)(?:="?([^"\]]+)"?)?\]$/);return m?m[2]===undefined?this.getAttribute(m[1])!==null:this.getAttribute(m[1])===m[2]:this.tagName===selector.toUpperCase();});}
 querySelectorAll(query){return this.children.flatMap(c=>[...(c.matches(query)?[c]:[]),...c.querySelectorAll(query)]);}click(){this.clicked++;}closest(){return null;}
}
function setup({path='/anchor/review',text='',children=[],query=''}={}){
 const body=new Element('body',text,{},children);globalThis.document={readyState:'complete',body,querySelectorAll:q=>body.querySelectorAll(q),querySelector:q=>body.querySelectorAll(q)[0]||null,getElementById:()=>null};globalThis.window={};globalThis.location=new URL('https://anchor.douyin.com'+path+query);globalThis.getComputedStyle=e=>({display:'block',visibility:'visible',cursor:e.attrs.cursor||'auto'});
 const operation=(action,payload={})=>pageOperation(action,SELECTORS,'REGRESSION',payload);return {body,operation,init(){const info=operation('inspect');operation('init',{live_key:info.live_key});return info;}};
}
const menu=(text,attrs={class:'side-menu-item'})=>new Element('div','',attrs,[new Element('span',text)]);
test('正确 /anchor/review 无按钮仍 OK，身份不依赖 selector',()=>{const f=setup();const r=f.operation('inspect');assert.equal(r.status,'OK');assert.deepEqual(r.page_diagnostic,{pathname:'/anchor/review',route_match:true,review_text_found:false,overview_found:false,content_found:false});});
test('React 右侧四模块 span 文本 / 父 div 点击',()=>{const labels=['整体数据','内容分析','观众分析','流量分析'],items=labels.map(t=>menu(t));const f=setup({text:'直播复盘',children:items});f.init();for(const [i,id]of ['overview','content','audience','traffic'].entries()){assert.equal(f.operation('find',{id}).status,'FOUND');assert.equal(f.operation('click',{id}).status,'CLICKED');assert.equal(items[i].clicked,1);assert.equal(items[i].children[0].clicked,0);}});
test('非 button span 使用最近 pointer/tabindex/role 可点击父级',()=>{for(const attrs of [{cursor:'pointer'},{tabindex:'0'},{role:'button'},{class:'extra side-menu-item selected'}]){const leaf=new Element('span','整 体 数据');const nearest=new Element('div','',attrs,[leaf]);const outer=new Element('div','',{cursor:'pointer'},[nearest]);const f=setup({children:[outer]});f.init();f.operation('click',{id:'overview'});assert.equal(nearest.clicked,1);assert.equal(outer.clicked,0);assert.equal(leaf.clicked,0);}});
test('两个同名目标 AMBIGUOUS，不随机点击；稳定 selector 也不能掩盖歧义',()=>{const a=menu('整体数据',{'data-probe-action':'overview',class:'side-menu-item'}),b=menu('整体数据');const f=setup({children:[a,b]});f.init();assert.equal(f.operation('find',{id:'overview'}).status,'AMBIGUOUS');assert.equal(f.operation('click',{id:'overview'}).status,'AMBIGUOUS');assert.equal(a.clicked+b.clicked,0);});
test('错误 /other 无复盘特征 NOT_REVIEW，安全诊断不保存 Query',()=>{const f=setup({path:'/other',query:'?room_id=PRIVATE_ROOM&token=PRIVATE_TOKEN'});const r=f.operation('inspect');assert.equal(r.status,'NOT_REVIEW');assert.equal(r.page_diagnostic.route_match,false);assert(!JSON.stringify(r.page_diagnostic).includes('PRIVATE'));});
test('异步未渲染 / 控件缺失由导航阶段 SKIPPED，页面始终 OK',async()=>{const f=setup();f.init();assert.equal(f.operation('inspect').status,'OK');const navigator=new ReviewNavigator({find:async id=>f.operation('find',{id}),click:async()=>assert.fail('must not click')},{},new AbortController().signal,{elementTimeout:0});assert.equal((await navigator.visit('overview')).reason,'SKIPPED_NOT_AVAILABLE');assert.equal(f.operation('inspect').status,'OK');const item=menu('整体数据');item.parentElement=f.body;f.body.children.push(item);assert.equal(f.operation('find',{id:'overview'}).status,'FOUND');});
test('文字必须精确匹配，不点整体数据说明/大页面容器/无点击标记 span',()=>{for(const children of [[menu('整体数据说明')],[new Element('span','整体数据')],[new Element('main','',{cursor:'pointer'},[new Element('span','整体数据')])]]){const f=setup({children});f.init();assert.equal(f.operation('click',{id:'overview'}).status,'SKIPPED_NOT_AVAILABLE');}});
test('祖先最多 6 层，隐藏目标不参与歧义',()=>{const root=menu('整体数据'),hidden=menu('整体数据',{class:'side-menu-item',hidden:true});const f=setup({children:[root,hidden]});f.init();assert.equal(f.operation('find',{id:'overview'}).status,'FOUND');let node=new Element('span','内容分析');for(let i=0;i<7;i++)node=new Element('div','',{},[node]);const ancestor=new Element('div','',{cursor:'pointer'},[node]);const g=setup({children:[ancestor]});g.init();assert.equal(g.operation('find',{id:'content'}).status,'SKIPPED_NOT_AVAILABLE');});
test('已知 review/replay 路由命中，不能模糊匹配 review-other',()=>{for(const path of ['/anchor/review/details','/anchor/replay','/review'])assert.equal(setup({path}).operation('inspect').status,'OK');assert.equal(setup({path:'/anchor/review-other'}).operation('inspect').status,'NOT_REVIEW');});
test('AMBIGUOUS 导航立即 SKIPPED，不能点击或随机重试',async()=>{let finds=0;const n=new ReviewNavigator({find:async()=>{finds++;return {status:'AMBIGUOUS'};},click:async()=>assert.fail('must not click')},{},new AbortController().signal);assert.deepEqual(await n.visit('overview'),{status:'SKIPPED',reason:'AMBIGUOUS'});assert.equal(finds,1);});
test('NOT_REVIEW 报告保留安全诊断，不保留 live_key / query 身份',async()=>{const f=setup({path:'/other',query:'?room_id=PRIVATE_ROOM'});const runner=new AutoCollector({attach:async()=>{},detach:async()=>{},page:{inspect:async()=>f.operation('inspect'),cancel:async()=>{}},navigator:{},summary:()=>({}),coverage:()=>({})});const report=await runner.run();assert.equal(report.errors[0].reason,'NOT_REVIEW');assert.equal(report.page_diagnostic.route_match,false);assert(!JSON.stringify(report).includes('PRIVATE_ROOM'));});
