import test from 'node:test';import assert from 'node:assert/strict';
import {pageOperation,PageController} from '../extension/src/automation/page-controller.js';
import {SELECTORS} from '../extension/src/automation/selectors.js';
import {waitForDOMReady,inspectReady} from '../extension/src/automation/wait-strategy.js';
import {ReviewNavigator} from '../extension/src/automation/review-navigator.js';
import {AutoCollector} from '../extension/src/automation/collector-state-machine.js';
function dom(state='complete',body={innerText:'',childElementCount:0}){globalThis.window={};globalThis.location=new URL('https://anchor.douyin.com/anchor/review?token=PRIVATE');globalThis.document={readyState:state,body,querySelectorAll:()=>[],querySelector:()=>null};return (a,p={})=>pageOperation(a,SELECTORS,'R',p);}
function clock(){let now=0;return {now:()=>now,pause:async ms=>{now+=ms;},timeout:1000,poll:100};}
test('null body readiness reports DOM_NOT_READY without scanning',()=>{const op=dom('loading',null);document.querySelectorAll=()=>assert.fail('no scan');assert.equal(op('readiness').status,'DOM_NOT_READY');assert.equal(op('inspect').status,'DOM_NOT_READY');});
test('document absent is safe',()=>{const op=dom();delete globalThis.document;assert.equal(op('readiness').has_document,false);assert.equal(op('inspect').status,'DOM_NOT_READY');});
test('loading body does not trigger control scanning',()=>{const op=dom('loading');document.querySelectorAll=()=>assert.fail('no scan');assert.equal(op('inspect').status,'DOM_NOT_READY');});
test('interactive and complete readiness passes with safe diagnostics',()=>{for(const state of ['interactive','complete']){const op=dom(state);const r=op('readiness');assert.equal(r.status,'OK');assert.equal(r.ready_state,state);assert(!JSON.stringify(r).includes('PRIVATE'));}});
test('body appears at 600ms, bounded polling observes ready',async()=>{const options=clock();let calls=0;await waitForDOMReady({readiness:async()=>{calls++;return {status:options.now()>=600?'OK':'DOM_NOT_READY'};}},options);assert.equal(options.now(),600);assert.equal(calls,7);});
test('DOM readiness timeout is bounded',async()=>{const options=clock();await assert.rejects(waitForDOMReady({readiness:async()=>({status:'DOM_NOT_READY'})},options),e=>e.code==='TIMEOUT');assert(options.now()<=1100);});
test('destroyed execution context retries inspect',async()=>{let calls=0;const page=new PageController(async()=>{if(++calls<3)throw Error('Execution context was destroyed token=PRIVATE');return {result:{value:{status:'OK'}}};},1,'R');const r=await inspectReady(page,clock());assert.equal(r.status,'OK');assert.equal(calls,3);});
test('permanent TypeError fails with action and sanitized coordinates',async()=>{const page=new PageController(async()=>({exceptionDetails:{exception:{description:'TypeError: token=PRIVATE'},lineNumber:42,columnNumber:8}}),1,'R');await assert.rejects(page.inspect(),e=>e.code==='DOM_ERROR'&&e.dom_action==='inspect'&&e.exception_type==='TYPE_ERROR'&&e.lineNumber===42&&!e.message.includes('PRIVATE'));});
test('Runtime send rejection classifies click action without raw error',async()=>{const page=new PageController(async()=>{throw Error('ReferenceError PRIVATE');},1,'R');await assert.rejects(page.click('overview'),e=>e.dom_action==='click:overview'&&e.exception_type==='REFERENCE_ERROR'&&!JSON.stringify(e).includes('PRIVATE'));});
test('null body during bound and signature never raises TypeError',()=>{const op=dom('complete',null);assert.equal(op('inspect').status,'DOM_NOT_READY');assert.equal(op('signature',{before_init:true}).status,'DOM_NOT_READY');dom();assert.equal(pageOperation('inspect',SELECTORS,'R').live_start,null);});
test('prepare waits React evidence and does not initialize',async()=>{let calls=0,inits=0;const activity={navigation:0,requests:new Set(),processing:0,lastActivity:0};const page={reload:async()=>activity.navigation++,readiness:async()=>({status:'OK'}),inspect:async()=>({status:'OK',live_key:'same',page_diagnostic:{content_found:++calls>=3}}),signature:async pre=>{assert.equal(pre,true);return 'stable';},init:async()=>inits++};const n=new ReviewNavigator(page,activity,undefined,{timeout:2000,minimum:0,quiet:0});const info=await n.prepare({live_key:'same'});assert.equal(info.live_key,'same');assert(calls>=3);assert.equal(inits,0);});
test('collector owns one init and preserves permanent DOM failure diagnostic',async()=>{let inits=0;const page={inspect:async()=>({status:'OK',live_key:'same'}),init:async()=>inits++,cancel:async()=>{}};const runner=new AutoCollector({attach:async()=>{},detach:async()=>{},page,navigator:{prepare:async p=>p,visit:async()=>{throw Object.assign(Error('safe'),{code:'DOM_ERROR',dom_action:'signature',exception_type:'TYPE_ERROR'});}},summary:()=>({endpoint_count:0}),coverage:()=>({coverage_ratio:0})});const r=await runner.run();assert.equal(inits,1);assert.equal(r.status,'FAIL');assert.equal(r.errors[0].dom_action,'signature');});
