import test from 'node:test';import assert from 'node:assert/strict';
import {safeRoomStatsContext} from '../extension/src/lib/room-stats-context.js';
import {metadata,capture} from '../extension/src/background/network-capture.js';
import {summaryFor} from '../extension/src/automation/session-analysis.js';
import {moduleEvidence,commentStatus} from '../extension/src/automation/evidence-policy.js';
import {ReviewNavigator} from '../extension/src/automation/review-navigator.js';
import {NetworkActivity} from '../extension/src/automation/wait-strategy.js';
import {exportFiles,zip} from '../extension/src/lib/exporter.js';
import {AutoCollector} from '../extension/src/automation/collector-state-machine.js';
const raw=q=>'https://anchor.douyin.com/api/room_stats_content_list?'+q;
const store=()=>({endpoints:{},bodyBytes:0,droppedBodies:0,counters:{},allowLarge:false});
async function add(s,name,step='initial',data={data:{}},options={}){const m={host:'anchor.douyin.com',path:'/api/'+name,method:'GET',context:{run_id:'RUN',step},body_status:'SAVE',...options};await capture(s,m,data===null?undefined:{body:JSON.stringify(data)});return m;}
const texts=()=>({data:{series:Array.from({length:4},(_,i)=>({content:'业务话术 '+i,contentTime:new Date(Date.parse('2026-09-30T02:06:32Z')+i*20000).toISOString()}))}});
function fakeClock(){let time=0;return {now:()=>time,pause:async ms=>{time+=ms;},textEffectTimeout:200};}
test('prefetch 正确归属四模块，step 与 prefetch 可同时观察',async()=>{const s=store();for(const name of ['overview_v3','entrance_v2','age_profile','room_stats_content_list'])await add(s,name);const r=summaryFor(s,'RUN');for(const id of ['overview','traffic','audience','content'])assert.equal(moduleEvidence(id,r.module_data).data_status,'PREFETCH_OBSERVED');await add(s,'overview_v3','overview');assert.equal(moduleEvidence('overview',summaryFor(s,'RUN').module_data).data_status,'STEP_AND_PREFETCH_OBSERVED');assert.equal(moduleEvidence('overview',{overview:['overview_v3']}).data_status,'STEP_OBSERVED');assert.equal(moduleEvidence('content',{gifts:['gift_top_v2'],clips:['key_fragment'],text:['room_stats_content_list']}).data_status,'STEP_OBSERVED');});
test('aux BODY_UNAVAILABLE 只产生 warning，不增加 core loss',async()=>{const s=store();for(const name of ['get_observe_permission','check','review','get_anchor_card'])await add(s,name,'initial',null,{body_status:'BODY_UNAVAILABLE'});const r=summaryFor(s,'RUN');assert.equal(r.capture_loss_count,4);assert.equal(r.core_capture_loss_count,0);assert.equal(r.aux_capture_loss_count,4);assert.equal(r.capture_warnings[0].reason,'AUXILIARY_CAPTURE_LOSS');});
test('core BODY_UNAVAILABLE 增加 core loss，且按 run 隔离',async()=>{const s=store();await add(s,'minute_trend','initial',null,{body_status:'BODY_UNAVAILABLE'});assert.equal(summaryFor(s,'RUN').core_capture_loss_count,1);assert.equal(summaryFor(s,'OTHER').core_capture_loss_count,0);});
test('roomStatsContentType 只接受短枚举，拒绝自由文本、凭据、重复键',()=>{for(const type of ['1','123','ANCHOR_TEXT','comment-v2'])assert.equal(safeRoomStatsContext(raw('roomStatsContentType='+type)).roomStatsContentType,type);for(const type of ['free text','Bearer-xxx','a'.repeat(33),'汉字'])assert.deepEqual(safeRoomStatsContext(raw('roomStatsContentType='+encodeURIComponent(type))),{});assert.deepEqual(safeRoomStatsContext(raw('roomStatsContentType=1&roomStatsContentType=2')),{});});
test('roomID 与所有身份凭据永远不保存值，endpoint 专用规则',()=>{const q='roomID=PRIVATE_ROOM&anchorID=PRIVATE_ANCHOR&uid=PRIVATE_UID&sec_uid=PRIVATE_SEC&token=PRIVATE_TOKEN&roomStatsContentType=1';const r=safeRoomStatsContext(raw(q));assert.deepEqual(r,{roomStatsContentType:'1'});assert(!JSON.stringify(r).includes('PRIVATE'));assert.deepEqual(safeRoomStatsContext('https://anchor.douyin.com/api/other?'+q),{});});
test('合法 start/end 转 ISO，支持中国墙上时间与 epoch',()=>{const r=safeRoomStatsContext(raw('startTime=2026-09-30%2010:06:32&endTime=2026-09-30T03:56:38Z'));assert.deepEqual(r,{startTime:'2026-09-30T02:06:32.000Z',endTime:'2026-09-30T03:56:38.000Z'});assert.equal(safeRoomStatsContext(raw('startTime=1790733992')).startTime,new Date(1790733992000).toISOString());});
test('非法日期、时间、时区、重复 start 不保存',()=>{for(const value of ['2026-02-30T10:00:00','2026-09-30T25:01:01','tomorrow','2026-09-30T10:00:00+99:00','0','2026-09-30T10:00:00Z SECRET'])assert.deepEqual(safeRoomStatsContext(raw('startTime='+encodeURIComponent(value))),{});assert.deepEqual(safeRoomStatsContext(raw('startTime=1790733992&startTime=1790733993')),{});});
test('metadata 持久化 normalized safe_business_context，不保存 raw query',()=>{const r=metadata({response:{url:raw('roomID=PRIVATE&roomStatsContentType=2&startTime=2026-09-30T02:06:32Z'),mimeType:'application/json'},type:'XHR'},'GET',{businessHosts:['anchor.douyin.com'],telemetryHosts:[]});assert.equal(r.safe_business_context.roomStatsContentType,'2');assert(!JSON.stringify(r).includes('PRIVATE'));});
test('text attempts 精确记录 reset/advance、new records 与 Network delta',async()=>{let records=90,sig=0;const a=new NetworkActivity();a.endpoints.set('room_stats_content_list',4);const page={signature:async()=>sig,textReset:async()=>({status:'AT_START',method:'time_range'}),textAdvance:async excluded=>{if(excluded.includes('time_range'))return {status:'SKIPPED_NOT_AVAILABLE',method:'none'};records+=10;sig++;a.received('room_stats_content_list');return {status:'ADVANCED',method:'time_range'};}};const n=new ReviewNavigator(page,a,undefined,fakeClock());n.settle=async()=>{};const r=await n.collectText(()=>({record_count:records,coverage_ratio:records/110}),{maxWindows:4});const attempt=r.attempts.find(x=>x.action==='advance');assert.equal(attempt.new_records,10);assert.equal(attempt.network_response_delta,1);assert.equal(attempt.room_stats_content_list_count_before,4);assert.equal(attempt.dom_signature_changed,true);assert.equal(r.reason,'COVERAGE_REACHED');assert(r.attempts.every(x=>Number.isInteger(x.elapsed_ms)&&x.elapsed_ms>=0));});
test('slider 完全无 Network 效果后切换机制，有限停止',async()=>{let calls=0;const page={signature:async()=>0,textReset:async()=>({status:'SKIPPED_NOT_AVAILABLE',method:'none'}),textAdvance:async excluded=>{calls++;for(const method of ['role_slider:ArrowRight','role_slider:PageDown','role_slider:End','scroll'])if(!excluded.includes(method))return {status:'ADVANCED',method};return {status:'SKIPPED_NOT_AVAILABLE',method:'none'};}};const n=new ReviewNavigator(page,new NetworkActivity(),undefined,fakeClock());n.settle=async()=>{};const r=await n.collectText(()=>({record_count:90,coverage_ratio:0.27}));assert.equal(calls,5);assert.equal(r.attempts.filter(a=>a.status==='NO_NETWORK_EFFECT').length,4);assert.equal(r.reason,'NO_NETWORK_EFFECT');});
test('comments 四态，不把未知类型或无 Response 误判空',async()=>{assert.equal(commentStatus({comment_timeline_count:1},{status:'PASS'}),'OBSERVED');assert.equal(commentStatus({comment_available_empty:true},{status:'PASS'}),'AVAILABLE_EMPTY');assert.equal(commentStatus({},{status:'PASS'}),'NOT_OBSERVED');assert.equal(commentStatus({},{status:'SKIPPED',reason:'SKIPPED_NOT_AVAILABLE'}),'NOT_AVAILABLE');assert.equal(commentStatus({},{status:'SKIPPED',reason:'AMBIGUOUS'}),'NOT_OBSERVED');const s=store();await add(s,'room_stats_content_list','comments',{data:{series:[]}},{safe_business_context:{roomStatsContentType:'UNKNOWN'}});assert.equal(summaryFor(s,'RUN').comment_available_empty,false);await add(s,'room_stats_content_list','text',texts(),{safe_business_context:{roomStatsContentType:'TEXT'}});assert.equal(summaryFor(s,'RUN').comment_available_empty,false);await add(s,'room_stats_content_list','initial',{data:{series:[{comment:'虚构评论',createTime:'2026-09-30T02:06:32Z',nickname:'虚构用户'}]}},{safe_business_context:{roomStatsContentType:'KNOWN_COMMENT'},context:{run_id:'PREVIOUS_RUN',step:'comments'}});await add(s,'room_stats_content_list','comments',{data:{series:[]}},{safe_business_context:{roomStatsContentType:'KNOWN_COMMENT'}});assert.equal(summaryFor(s,'RUN').comment_available_empty,true);assert.equal(commentStatus(summaryFor(s,'RUN'),{status:'PASS'}),'AVAILABLE_EMPTY');});
test('相同 text content type 空 Response 不能作为 comments 空证据',async()=>{const s=store();await add(s,'room_stats_content_list','text',texts(),{safe_business_context:{roomStatsContentType:'SAME'}});await add(s,'room_stats_content_list','comments',{data:{series:[]}},{safe_business_context:{roomStatsContentType:'SAME'}});assert.equal(summaryFor(s,'RUN').comment_available_empty,false);});
test('fans AMBIGUOUS 与 prefetch 数据状态独立',async()=>{const s=store();await add(s,'fans_group_pie');assert.equal(moduleEvidence('fans',summaryFor(s,'RUN').module_data).data_status,'PREFETCH_OBSERVED');});
test('share-safe ZIP 删除身份字段、账号 name、嵌套身份，保留业务话术和指标 name',async()=>{const s=store();await add(s,'overview_v3','initial',{data:{user:{name:'PRIVATE_ACCOUNT',user_id:'PRIVATE_ID',sec_uid:'PRIVATE_SEC',nickname:'PRIVATE_NICK',avatar:'https://example.com/PRIVATE_AVATAR'},account:JSON.stringify({userID:'PRIVATE_NESTED',name:'PRIVATE_NAME'}),author:JSON.stringify({name:'PRIVATE_ONLY_NAME'}),metric:{name:'GMV',value:12},series:[{content:'保留业务话术',contentTime:'2026-09-30T02:06:32Z'}]}});const packed=exportFiles(s,{shareSafe:true});const text=Object.values(packed.files).join('\n');for(const needle of ['PRIVATE_ACCOUNT','PRIVATE_ID','PRIVATE_SEC','PRIVATE_NICK','PRIVATE_AVATAR','PRIVATE_NESTED','PRIVATE_NAME','PRIVATE_ONLY_NAME','user_id','sec_uid','nickname','avatar'])assert(!text.includes(needle),needle);assert(text.includes('保留业务话术'));assert(text.includes('GMV'));assert(new Uint8Array(await zip(packed.files).arrayBuffer()).length>0);assert(Object.keys(packed.files).some(x=>x.includes('_ShareSafe/')));});
test('share-safe export 不修改原始 session 或本地诊断包',async()=>{const s=store();await add(s,'room_base','initial',{data:{user_id:'PRIVATE_LOCAL',name:'LOCAL_ACCOUNT'}});const before=JSON.stringify(s);exportFiles(s,{shareSafe:true});assert.equal(JSON.stringify(s),before);assert(Object.values(exportFiles(s).files).join('').includes('PRIVATE_LOCAL'));});
async function reportWith({coreLoss=0,auxLoss=0,comments='empty'}={}){const r=new AutoCollector({attach:async()=>{},detach:async()=>{},page:{inspect:async()=>({status:'OK'}),init:async()=>{},cancel:async()=>{}},navigator:{visit:async id=>({status:id==='fans'?'SKIPPED':id==='comments'&&comments==='missing'?'SKIPPED':'PASS',reason:id==='fans'?'AMBIGUOUS':id==='comments'&&comments==='missing'?'SKIPPED_NOT_AVAILABLE':undefined}),collectText:async()=>({})},summary:()=>({endpoint_count:4,core_capture_loss_count:coreLoss,aux_capture_loss_count:auxLoss,capture_loss_count:coreLoss+auxLoss,comment_available_empty:comments==='empty',comment_timeline_count:comments==='observed'?1:0,captured_endpoints:['minute_trend','overview_v3','entrance_v2','room_stats_content_list'],minute_trend_time_series:true,text_timeline_count:1,module_data:{initial:['overview_v3','entrance_v2','age_profile','room_stats_content_list','fans_group_pie']}}),coverage:()=>({record_count:331,coverage_ratio:1})});return r.run();}
test('整体 PASS 允许 aux loss + 空评论 / 无评论控件；core loss 或未知评论 PARTIAL',async()=>{assert.equal((await reportWith({auxLoss:7})).status,'PASS');assert.equal((await reportWith({comments:'missing'})).status,'PASS');assert.equal((await reportWith({coreLoss:1})).status,'PARTIAL');assert.equal((await reportWith({comments:'unknown'})).status,'PARTIAL');const r=await reportWith();assert.equal(r.modules.fans.navigation,'AMBIGUOUS');assert.equal(r.modules.fans.data_status,'PREFETCH_OBSERVED');});

test('share-safe 不将业务 content/name 的字面值误认为身份字段',async()=>{const s=store();await add(s,'analysis_v3','content',{data:{series:[{content:'uid',contentTime:'2026-09-30T02:06:32Z'}],metric:{name:'nickname',value:7}}});const response=Object.entries(exportFiles(s,{shareSafe:true}).files).find(([name])=>name.includes('/responses/'))[1];const body=JSON.parse(response);assert.equal(body.data.series[0].content,'uid');assert.equal(body.data.metric.name,'nickname');});
