import test from 'node:test';import assert from 'node:assert/strict';
import {capture} from '../extension/src/background/network-capture.js';
import {summaryFor,coverageFor} from '../extension/src/automation/session-analysis.js';
import {transcriptSnapshot,speechEvidence} from '../extension/src/automation/transcript-evidence.js';
import {collectTranscript} from '../extension/src/automation/transcript-scroll.js';
import {AutoCollector} from '../extension/src/automation/collector-state-machine.js';
import fs from 'node:fs';
const base=Date.parse('2026-09-30T02:06:32Z');const page={live_start:new Date(base).toISOString(),live_end:new Date(base+6600000).toISOString()};
const rows=(start,count=90)=>Array.from({length:count},(_,i)=>({content:'虚构主播口播 '+(start+i),contentTime:new Date(base+(start+i)*20000).toISOString(),nickname:'单一虚构主播',userID:'0',secUid:''}));
const session=()=>({endpoints:{},bodyBytes:0,counters:{},allowLarge:false,droppedBodies:0});
async function window(s,offset,count=90,{type='4',start=offset*20000}={}){await capture(s,{host:'anchor.douyin.com',path:'/api/room_stats_content_list',method:'GET',body_status:'SAVE',context:{run_id:'RUN',step:'text'},safe_business_context:{roomStatsContentType:type,startTime:new Date(base+start).toISOString(),endTime:new Date(base+Math.min(6600000,start+1799000)).toISOString()}},{body:JSON.stringify({data:{series:rows(offset,count)}})});}
function simulation({cached=false,stuck=false,missing=false,repeatWindow=false}={}){let tick=0,index=missing?1:0,count=1,recordCount=90,last=base+index*1800000+1780000,scroll=0;const windows=[{startTime:new Date(base+index*1800000).toISOString(),endTime:new Date(base+(index+1)*1800000-1000).toISOString()}];const state=()=>({type4_request_count:count,windows,latest_window:windows.at(-1),window_count:windows.length,record_count:recordCount,coverage_ratio:recordCount>=331?1:0.27,start_window_missing:missing,live_end:page.live_end});const dom=()=>({status:'TRANSCRIPT_SCROLL_CONTAINER_CONFIRMED',scrollTop:scroll,scrollHeight:10000,clientHeight:200,visible_first_time:new Date(base+index*1800000).toISOString(),visible_last_time:new Date(last).toISOString(),row_count:90,ancestor_depth:1});const controller={transcriptFind:async()=>dom(),transcriptScroll:async()=>{if(stuck)return {...dom(),status:'NO_PROGRESS'};if(index>=3)return {...dom(),status:'AT_BOTTOM'};scroll+=160;index++;last=index===3?base+6600000:base+index*1800000+1780000;if(!cached){count++;if(!repeatWindow)windows.push({startTime:new Date(base+index*1800000).toISOString(),endTime:new Date(Math.min(base+6600000,base+(index+1)*1800000-1000)).toISOString()});recordCount=Math.min(331,recordCount+90);}return {...dom(),status:'SCROLLED'};}};return {controller,state,options:{now:()=>tick,pause:async ms=>tick+=ms,transcriptWaitTimeout:100},progress:()=>({record_count:recordCount,coverage_ratio:state().coverage_ratio})};}
test('type4 连续20秒、单说话人、占位身份为 speech，不是 comment',async()=>{const s=session();await window(s,0);const r=summaryFor(s,'RUN',page);assert.equal(r.room_stats_type_evidence['4'].classification,'SPEECH_TRANSCRIPT_CANDIDATE');assert.equal(r.comment_timeline_count,0);assert.equal(r.full_transcript_timeline.record_count,90);assert(Object.values(s.endpoints)[0].schema.arrays.some(a=>a.speech_transcript&&!a.comment_timeline));});
test('type1/type2 语义仍 UNKNOWN；真实不同用户的 type4 不强判 speech',()=>{assert.equal(speechEvidence(rows(0),'1').classification,'UNKNOWN');assert.equal(speechEvidence(rows(0),'2').classification,'UNKNOWN');assert.equal(speechEvidence(rows(0).map((r,i)=>({...r,userID:String(i+1)})),'4').classification,'UNKNOWN');assert.equal(speechEvidence(rows(0).map(r=>({...r,userId:'REAL_USER'})),'4').classification,'UNKNOWN');});
test('type4 多窗口合并去重，正式正文只含content/contentTime',async()=>{const s=session();await window(s,0);await window(s,80);await window(s,0);assert.equal(transcriptSnapshot(s,'RUN',page).record_count,170);assert.equal(transcriptSnapshot(s,'RUN',page).window_count,2);assert.deepEqual(Object.keys(s.full_transcript_timelines.RUN.records[0]).sort(),['content','contentTime']);});
test('4个真实窗口合并至95%以上，不由首尾伪造',async()=>{const s=session();await window(s,0);await window(s,90);await window(s,180);await window(s,270,61);const r=transcriptSnapshot(s,'RUN',page);assert.equal(r.record_count,331);assert.equal(r.coverage_ratio,1);assert.equal(r.start_window_missing,false);});
test('起始窗口在直播中段，必须start window missing',async()=>{const s=session();await window(s,90);assert.equal(transcriptSnapshot(s,'RUN',page).start_window_missing,true);});
test('滚动窗口count+start/end变化才 WINDOW_ADVANCED，直到95%停止',async()=>{const f=simulation();const r=await collectTranscript(f.controller,f.progress,f.state,async()=>{},undefined,f.options);assert.equal(r.reason,'COVERAGE_REACHED');assert.equal(r.transcript_scroll_attempts.length,3);assert(r.transcript_scroll_attempts.every(a=>a.status==='WINDOW_ADVANCED'&&a.evidence==='TRANSCRIPT_WINDOW_ADVANCED'));});
test('新Response但同一窗口不能 WINDOW_ADVANCED',async()=>{const f=simulation({repeatWindow:true});const r=await collectTranscript(f.controller,f.progress,f.state,async()=>{},undefined,f.options,{maxWindows:1});assert.notEqual(r.transcript_scroll_attempts[0].status,'WINDOW_ADVANCED');});
test('DOM进展无Network时继续，正式record_count不增加；结束标 cached partial',async()=>{const f=simulation({cached:true});const r=await collectTranscript(f.controller,f.progress,f.state,async()=>{},undefined,f.options);assert(r.transcript_scroll_attempts.filter(a=>a.status==='DOM_PROGRESS_ONLY').length>=3);assert.equal(r.full_transcript_timeline.record_count,90);assert.equal(r.reason,'PARTIAL_CACHED_BEFORE_CAPTURE');});
test('完全无进展只尝试有限3次',async()=>{const f=simulation({stuck:true});const r=await collectTranscript(f.controller,f.progress,f.state,async()=>{},undefined,f.options);assert.equal(r.reason,'NO_PROGRESS');assert.equal(r.transcript_scroll_attempts.length,3);});
test('物理小步滚动允许继续等lazy阈值，无效机制不调用slider/API',async()=>{const f=simulation();let clicks=0;f.controller.transcriptScroll=async()=>({status:'SCROLLED',scrollTop:++clicks*160,scrollHeight:10000,clientHeight:200,visible_last_time:(await f.controller.transcriptFind()).visible_last_time});const r=await collectTranscript(f.controller,f.progress,f.state,async()=>{},undefined,f.options,{maxWindows:5});assert.equal(r.transcript_scroll_attempts.length,5);assert.equal(r.reason,'WINDOW_LIMIT');assert(r.transcript_scroll_attempts.every(a=>a.status==='SCROLLED'));});
test('起始缺失即使后续覆盖率看似完整也不宣布完成',async()=>{const f=simulation({missing:true});const r=await collectTranscript(f.controller,f.progress,f.state,async()=>{},undefined,f.options);assert.equal(r.reason,'TRANSCRIPT_START_WINDOW_MISSING');});
test('新主链允许comments NOT_OBSERVED独立不阻塞；缺起始窗口仍PARTIAL',async()=>{for(const missing of [false,true]){const full={record_count:331,window_count:4,window_sequence_valid:true,coverage_ratio:1,start_window_missing:missing,coverage:{record_count:331,coverage_ratio:1}};const r=new AutoCollector({attach:async()=>{},detach:async()=>{},page:{inspect:async()=>({status:'OK'}),init:async()=>{},cancel:async()=>{}},navigator:{visit:async()=>({status:'PASS'}),collectText:async()=>({transcript_scroll_attempts:[{status:'WINDOW_ADVANCED'}],full_transcript_timeline:full})},summary:()=>({endpoint_count:4,captured_endpoints:['minute_trend','overview_v3','room_stats_content_list','entrance_v2'],minute_trend_time_series:true,text_timeline_count:1,core_capture_loss_count:0,comment_timeline_count:0}),coverage:()=>({coverage_ratio:1})});const report=await r.run();assert.equal(report.modules.comments.data_status,'NOT_OBSERVED');assert.equal(report.status,missing?'PARTIAL':'PASS');}});
test('扩展不构造业务请求、不改视频、不使用坐标；80%列表增量代码',()=>{const text=fs.readFileSync('extension/src/automation/transcript-dom.js','utf8');assert(text.includes('e.clientHeight*0.8'));for(const f of ['transcript-dom.js','transcript-scroll.js','transcript-evidence.js'])assert(!/fetch\s*\(|XMLHttpRequest|currentTime\s*=|getBoundingClientRect|dispatchMouseEvent/.test(fs.readFileSync('extension/src/automation/'+f,'utf8')));});

test('type4空窗口保留真实范围，但不补造正式正文或评论',async()=>{const s=session();await capture(s,{host:'anchor.douyin.com',path:'/api/room_stats_content_list',method:'GET',context:{run_id:'RUN',step:'text'},safe_business_context:{roomStatsContentType:'4',startTime:page.live_start,endTime:new Date(base+1799000).toISOString()}},{body:JSON.stringify({data:{series:[]}})});const r=transcriptSnapshot(s,'RUN',page);assert.equal(r.window_count,1);assert.equal(r.record_count,0);await window(s,0,331,{type:'1'});assert.equal(coverageFor(s,'RUN',page).record_count,0);assert.equal(summaryFor(s,'RUN',page).comment_timeline_count,0);});
