import test from 'node:test';import assert from 'node:assert/strict';
import {transcriptDOM} from '../extension/src/automation/transcript-dom.js';
import {PageController} from '../extension/src/automation/page-controller.js';
import {sampleExpectedTimes,safeExpectedTimes} from '../extension/src/automation/expected-transcript-times.js';
import {collectTranscript} from '../extension/src/automation/transcript-scroll.js';
class E{
 constructor(tag,text='',attrs={},children=[]){this.tagName=tag.toUpperCase();this.text=text;this.attrs=attrs;this.children=children;this.scrollTop=0;this.clientHeight=attrs.height||40;this.scrollHeight=attrs.scroll||this.clientHeight;for(const child of children)child.parentElement=this;}
 get textContent(){return this.text+this.children.map(c=>c.textContent).join('');}get innerText(){return this.textContent;}
 getAttribute(k){return this.attrs[k]??null;}getClientRects(){return this.attrs.hidden?[]:[{top:0,bottom:this.clientHeight}];}
 contains(e){return e===this||this.children.some(c=>c.contains(e));}
 matches(query){return query.split(',').some(raw=>{const q=raw.trim();if(q.startsWith('.'))return (this.attrs.class||'').split(/\s+/).includes(q.slice(1));const m=q.match(/^\[([^=*\]]+)(\*?=)?"?([^"\]]*)"?\]$/);if(m)return !m[2]?this.getAttribute(m[1])!==null:m[2]==='*='?(this.getAttribute(m[1])||'').includes(m[3]):this.getAttribute(m[1])===m[3];return q.toUpperCase()===this.tagName;});}
 querySelectorAll(q){return this.children.flatMap(c=>[...(c.matches(q)?[c]:[]),...c.querySelectorAll(q)]);}
 dispatchEvent(){}
}
const times=['2026-09-30 11:21:36','2026-09-30 11:21:56','2026-09-30 11:22:16','2026-09-30 11:22:36'];
const iso=t=>new Date(Date.parse(t.replace(' ','T')+'+08:00')).toISOString();
function fixture({rowTimes=times,scroll=true,tag='div',decoy=true,embedded=true}={}){
 const rows=rowTimes.map(t=>new E('div','',{},[new E('span',(embedded?'PRIVATE_NICKNAME 团***销 ':'')+t),new E('p','PRIVATE_SPEECH_BODY')]));
 const list=new E(tag,'',{height:536,scroll:scroll?3960:536,overflow:scroll?'auto':'visible'},rows);
 const pane=new E('section','',{'data-probe-text-panel':''},[...(decoy?[new E('div','PRIVATE_DECOY',{height:100,scroll:1000,overflow:'auto'})]:[]),new E('div','',{height:700,scroll:6000,overflow:'auto'},[list])]);
 const body=new E('body','',{},[new E('button','文字记录'),pane]);globalThis.document={querySelectorAll:q=>body.querySelectorAll(q),getElementById:()=>null,scrollingElement:body};globalThis.getComputedStyle=e=>({display:'block',visibility:'visible',overflowY:e.attrs.overflow||'visible'});
 return {list,pane,rows,find:(expected=[])=>transcriptDOM('find',expected)};
}
test('嵌入昵称的合法时间戳可提取，诊断不泄漏昵称正文',()=>{const f=fixture();const r=f.find(times.slice(0,3));assert.equal(r.status,'TRANSCRIPT_SCROLL_CONTAINER_CONFIRMED');assert.equal(r.first_time,iso(times[0]));assert(!JSON.stringify(r).includes('PRIVATE'));assert(!JSON.stringify(r).includes('团***销'));});
test('多个时间戳的大容器不能伪造一个row；混合时间row拒绝',()=>{const f=fixture({rowTimes:[times[0]+' '+times[1],times[1]+' '+times[2],times[2]+' '+times[3]]});const r=f.find(times);assert.equal(r.status,'TRANSCRIPT_SCROLL_CONTAINER_NOT_FOUND');assert.equal(r.transcript_find_diagnostic.row_groups_found,0);});
test('expectedTimes以包含方式匹配，并优先有至少两个已知时间的group',()=>{const f=fixture();const other=new E('div','',{height:200,scroll:1000,overflow:'auto'},['10:06:32','10:06:52','10:07:12'].map(t=>new E('div','',{},[new E('span','另一个名字 2026-09-30 '+t),new E('p','OTHER_PRIVATE_BODY')])));other.parentElement=f.pane;f.pane.children.unshift(other);const r=f.find(times);assert.equal(r.clientHeight,536);assert.equal(r.matched_expected_times_count,4);assert.equal(r.transcript_find_diagnostic.row_groups_found,2);});
test('至少3个严格递增siblings才能GROUP_CONFIRMED',()=>{for(const rowTimes of [times.slice(0,2),[times[2],times[1],times[0]],[times[0],times[0],times[1]]])assert.equal(fixture({rowTimes}).find(times).status,'TRANSCRIPT_SCROLL_CONTAINER_NOT_FOUND');const r=fixture({rowTimes:times.slice(0,3)}).find(times);assert.equal(r.row_group_status,'TRANSCRIPT_ROW_GROUP_CONFIRMED');assert.equal(r.row_count,3);});
test('最近scroll祖先优先，不选择前置诱饵或整个MAIN',()=>{const r=fixture().find(times);assert.equal(r.clientHeight,536);assert.equal(r.scrollHeight,3960);assert.equal(r.ancestor_depth,1);assert.equal(fixture({tag:'main'}).find(times).status,'TRANSCRIPT_SCROLL_CONTAINER_NOT_FOUND');});
test('失败也有六项纯数字计数诊断',()=>{const f=fixture({rowTimes:['非法时间','2026-02-30 11:00:00','2026-09-30 25:00:00']});const r=f.find(times);assert.equal(r.status,'TRANSCRIPT_SCROLL_CONTAINER_NOT_FOUND');assert.deepEqual(Object.keys(r.transcript_find_diagnostic),['expected_time_count','expected_time_matches','timestamp_nodes_found','row_candidates_found','row_groups_found','scrollable_ancestors_found']);assert(Object.values(r.transcript_find_diagnostic).every(Number.isInteger));assert(!JSON.stringify(r).includes('PRIVATE'));});
test('只取前中后最多12个北京时间，PageController拒绝正文/昵称对象及嵌入输入',async()=>{const all=Array.from({length:90},(_,i)=>new Date(Date.parse('2026-09-30T02:06:34Z')+i*20000).toISOString());const sampled=sampleExpectedTimes(all);assert.equal(sampled.length,12);assert.equal(sampled[0],'2026-09-30 10:06:34');assert.equal(sampled.at(-1),'2026-09-30 10:36:14');assert.deepEqual(safeExpectedTimes(['PRIVATE_NICK '+times[0],{content:'PRIVATE_BODY'},'2026-02-30 11:00:00']),[]);let expression;const page=new PageController(async(_,method,params)=>{expression=params.expression;return {result:{value:{status:'OK'}}};},1,'R');await page.transcriptFind([times[0],'PRIVATE_NICK '+times[1],{content:'PRIVATE_BODY'}]);assert(!expression.includes('PRIVATE'));assert(expression.includes('expectedTimes'));assert(expression.includes(times[0]));});
test('时间参数传递保留滚动逻辑，缓存未匹配时间仍可泛化定位',async()=>{const f=fixture();const r=f.find(['2026-09-30 10:06:34','2026-09-30 10:06:54']);assert.equal(r.status,'TRANSCRIPT_SCROLL_CONTAINER_CONFIRMED');assert.equal(r.matched_expected_times_count,0);let seen;const state=()=>({expected_times:times.slice(0,3),coverage_ratio:0,record_count:90,type4_request_count:1,window_count:1,latest_window:null});const dom={status:'TRANSCRIPT_SCROLL_CONTAINER_CONFIRMED',scrollTop:0,scrollHeight:3960,clientHeight:536};const page={transcriptFind:async t=>{seen=t;return dom;},transcriptScroll:async t=>{assert.deepEqual(t,times.slice(0,3));return {...dom,status:'AT_BOTTOM'};}};const result=await collectTranscript(page,()=>({}),state,async()=>{},undefined,{}, {maxWindows:1});assert.deepEqual(seen,times.slice(0,3));assert.equal(result.reason,'AT_BOTTOM');});
